services:
  - type: web
    name: final_year_project
    env: python
    buildCommand: "./build.sh"
    startCommand: "python3 manage.py runserver"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db.sqlite3
          property: connectionString
