# Generated by Django 5.2 on 2025-04-09 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_aigeneratedexam'),
        ('student', '0003_student_ai_usage_count_student_last_ai_interaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_selected', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField()),
                ('time_taken', models.PositiveIntegerField(help_text='Time taken in seconds')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='ResultAnalytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_time', models.PositiveIntegerField(help_text='Total time taken in seconds')),
                ('average_time_per_question', models.FloatField()),
                ('correct_answers', models.PositiveIntegerField()),
                ('incorrect_answers', models.PositiveIntegerField()),
                ('result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='quiz.result')),
            ],
        ),
    ]
