# Generated by Django 5.2 on 2025-04-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_alter_adaptivequizsettings_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='allow_backtracking',
            field=models.BooleanField(default=True, help_text='Whether students can go back to previous questions'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_timed',
            field=models.BooleanField(default=False, help_text='Whether this course has a time limit'),
        ),
        migrations.AddField(
            model_name='course',
            name='security_level',
            field=models.CharField(choices=[('low', 'Low - Basic protection'), ('medium', 'Medium - Prevent copy-paste and right-click'), ('high', 'High - Block dev tools and keyboard shortcuts')], default='medium', help_text='Level of security measures to prevent cheating', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='sequential_questions',
            field=models.BooleanField(default=False, help_text='Display questions one at a time sequentially'),
        ),
        migrations.AddField(
            model_name='course',
            name='total_time_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Total time allowed for the quiz in minutes (0 = unlimited)'),
        ),
    ]
