# Generated by Django 5.2 on 2025-04-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_aiadoptiondata_aiinsighttopic_insighttopic_aimodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ai_generation_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='multiple_answers',
            field=models.JSONField(blank=True, help_text='JSON array of correct answers for checkbox questions', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('checkbox', 'Checkbox (Multiple Answers)'), ('short_answer', 'Short Answer')], default='multiple_choice', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='short_answer_pattern',
            field=models.CharField(blank=True, help_text='Pattern or keywords for matching short answers', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, choices=[('Option1', 'Option1'), ('Option2', 'Option2'), ('Option3', 'Option3'), ('Option4', 'Option4')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
