# Generated by Django 5.2 on 2025-04-17 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_question_ai_generation_prompt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='confusion_matrix',
            field=models.JSONField(default=dict, help_text='Confusion matrix as a JSON array of arrays'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='f1_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='feature_importance',
            field=models.JSONField(default=dict, help_text='Feature importance as a JSON dictionary'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='features_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='precision',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='recall',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='roc_auc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='roc_curve_data',
            field=models.JSONField(default=dict, help_text='ROC curve data points'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='training_records_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CSVUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('success', 'Success'), ('error', 'Error')], default='processing', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processing_time', models.FloatField(blank=True, help_text='Processing time in seconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csv_uploads', to=settings.AUTH_USER_MODEL)),
                ('trained_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_uploads', to='quiz.aimodel')),
            ],
        ),
        migrations.AddField(
            model_name='aiadoptiondata',
            name='upload_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adoption_data', to='quiz.csvupload'),
        ),
    ]
