# Generated by Django 5.2 on 2025-04-17 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_aimodel_confusion_matrix_aimodel_f1_score_and_more'),
    ]

    operations = [
    ]
