# Generated by Django 5.2 on 2025-04-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_csvupload_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvupload',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='csvupload',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='csvupload',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='csvupload',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='csvupload',
            name='processing_time',
        ),
        migrations.RemoveField(
            model_name='csvupload',
            name='trained_model',
        ),
        migrations.RemoveField(
            model_name='csvupload',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='csvupload',
            name='record_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='csvupload',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
