# Generated by Django 5.2 on 2025-04-18 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_remove_csvupload_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiadoptiondata',
            name='upload_batch',
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='training_data',
        ),
        migrations.RemoveField(
            model_name='aiinsight',
            name='topic',
        ),
        migrations.DeleteModel(
            name='AIInsightTopic',
        ),
        migrations.RemoveField(
            model_name='aiprediction',
            name='model',
        ),
        migrations.RemoveField(
            model_name='csvupload',
            name='user',
        ),
        migrations.RemoveField(
            model_name='nlquery',
            name='user',
        ),
        migrations.DeleteModel(
            name='AIAdoptionData',
        ),
        migrations.DeleteModel(
            name='AIInsight',
        ),
        migrations.DeleteModel(
            name='InsightTopic',
        ),
        migrations.DeleteModel(
            name='AIModel',
        ),
        migrations.DeleteModel(
            name='AIPrediction',
        ),
        migrations.DeleteModel(
            name='CSVUpload',
        ),
        migrations.DeleteModel(
            name='NLQuery',
        ),
    ]
