# Generated by Django 5.1.7 on 2025-05-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_remove_prediction_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(default='', help_text='Course title', max_length=200),
        ),
    ]
